### PR TITLE
修正project name err

### PR DESCRIPTION
**Pull request by zhangxiaocong**
## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by antouhou** [comment]
The project name is correct in the `package.json`, it's name on the npm. It doesn't have to be the same as the repo name. https://www.npmjs.com/package/dash

**Comment by zhangxiaocong** [comment]
the problmem is that if you dont delete or change this name to diff with dash, it will prompt that an error (the project is the same with repository). please try in your webstorm again

**Comment by antouhou** [comment]
What error? Name of this package on npm is `dash`, it's the correct name, there's no mistake

**Comment by zhangxiaocong** [comment]
if you clone this project, and npm install  , you can find the err. believe me

**Comment by antouhou** [comment]
Can you post the error message you're getting?

**Comment by shumkov** [comment]
@zhangxiaocong Really sorry for closing your PR. It happened automatically when I remove `0.13-dev` branch that is part of our release flow. Could you please recreate it to `0.15-dev` please?

**Pull request closed without merging**
