### PR TITLE
docs: update @dashevo/dashjs references to dash

### PR DESCRIPTION
**Pull request by thephez**
### Issue being fixed or implemented  

Several references to @dashevo/dashjs remain in places that should just be "dash"

### What was done  

Updated readme to remove incorrect references

### How Has This Been Tested?

N/A

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by thephez** [comment]
Yes, I saw some confusion on Discord and figured this is probably where it came from since the readme tutorials all looked correct.

**Comment by thephez** [comment]
Oh, this PR should actually update some other docs or the docsify stuff is going to be incorrect too (e.g. https://github.com/dashevo/DashJS/tree/master/docs). Not able to do that where I am. 🙁

**Comment by seigler** [comment]
I did a project search/replace "@dashevo/dashjs" => "dash" and it only affected MD files. I didn't see any instances that looked wrong in the diff.

**Comment by Alex-Werner** [comment]
Thanks ! Wonderful, merging.

**Pull request merged**
